language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

install: true

script: 
 - pwd
 - ls -la
 - ls cmake/modules
 - cmake --version
 - mkdir build && cd build && cmake ..
 - make && make test
